### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by engramar** [codesydney/lloydconsulting#11]
As a start, let us just have the following in the navbar
- Home
- About
- Services
- Blog
- Shop
- Contact

Reference: http://imroz.rainbowit.net/dark-portfolio-landing#home
![image](https://user-images.githubusercontent.com/7553347/189505503-f38f6e75-0402-4946-9428-add4be21550a.png)

**Comment by davidtaing** [comment]
Closing this issue as we have removed most of the sections.
