### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by engramar** [codesydney/lloydconsulting#12]
Reference: http://imroz.rainbowit.net/dark-portfolio-landing#home
![image](https://user-images.githubusercontent.com/7553347/189505567-c6f5c925-5626-4ef7-9af2-ac65befc9e5f.png)

**Comment by davidtaing** [comment]
Hi @n4heen, do you need any help with this issue?

**Comment by n4heen** [comment]
I am all good with the about page @davidtaing. Just been busy with Uni exams at the moment. I will contribute to the about page during the weekend.

**Comment by davidtaing** [comment]
Closing this issue. If we have any follow up changes, let's create a new issue.
