### ISSUE TITLE
Services Page - ONGOING 

### ISSUE THREAD

**Issue by engramar** [codesydney/lloydconsulting#13]
Reference: http://imroz.rainbowit.net/dark-portfolio-landing#home
![image](https://user-images.githubusercontent.com/7553347/189505582-fb25994f-5546-4b1b-8a23-bfc0e8fbb8c8.png)

**Comment by LiviaFResende** [comment]
** Livia **

**Comment by davidtaing** [comment]
Hi @LiviaFResende, do you need any help with this issue?

**Comment by LiviaFResende** [comment]
Hi David, good morning.
I am on this issue right now, and I will let you know. Thank you

Could you please, move it to "in progress" column"?

**Comment by davidtaing** [comment]
No problems!

I don't have access to `in progress` column.

@engramar can you please assist when you get a chance?
