### ISSUE TITLE
Update Navbar Facebook Link

### ISSUE THREAD

**Issue by davidtaing** [codesydney/lloydconsulting#20]
Update the social links in the Navbar so that they direct the user to Dean's social media pages.

I think it would be better if the links open in new tabs. See here for more information: https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/

Note: I have to check if Dean has a Facebook page.

**Comment by LiviaFResende** [comment]
**Hi David,** I have checked the email and Dean has a Youtube Channel. Could we add this instead? Or create a issue for that one.
https://www.youtube.com/channel/UC2x2-XROxQMbehihLBVc53A

**Comment by davidtaing** [comment]
Sorry Livia,
I didn't see this message.

I think it would be best to check with Dean.

Looping @kathryn008 in the loop as well
