### ISSUE TITLE
Update Navbar LinkedIn Link

### ISSUE THREAD

**Issue by davidtaing** [codesydney/lloydconsulting#21]
Update the social links in the Navbar so that they direct the user to Dean's social media pages. 

I think it would be better if the links open in new tabs. See here for more information: https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/

Dean's LinkedIn Page: https://www.linkedin.com/in/dean-m-lloyd-criminalconsultant/

**Comment by davidtaing** [comment]
Hi @n4heen, would you like to take this one on?

**Comment by n4heen** [comment]
I will do this on just a simple link tag from react router dom.

**Comment by davidtaing** [comment]
Cool, cool. I've assigned you to this task.

Let me know if you have any questions or need help. 🙂
