### ISSUE TITLE
Update Navbar Instagram Link

### ISSUE THREAD

**Issue by davidtaing** [codesydney/lloydconsulting#22]
Update the social links in the Navbar so that they direct the user to Dean's social media pages. 

I think it would be better if the links open in new tabs. See here for more information: https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/

Dean's Instagram Page: https://www.instagram.com/consult_a_criminal/?hl=en

**Comment by davidtaing** [comment]
Assigned to @kathryn008.

**Comment by ghost** [comment]
!!! Please just ignore this pull request for now, I forgot to add the target attribute. I'll amend it and then figure out how to resubmit ; )

**Comment by davidtaing** [comment]
Oh, you should have left the PR open. You did a good job there.

Can you please reopen it? And add another commit to it? I'll add a comment in your PR to help you out.

Keep up the good work.
