### ISSUE TITLE
Blog page links 

### ISSUE THREAD

**Issue by ghost** [codesydney/lloydconsulting#37]
Currently when you click on the cards in the blog page section, they link to an internal template blog page. 

The links need to send the user to external media sources (ABC news, LinkedIn article, Youtube). 

Also, please do this while keeping Dean's main page open: 
https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/

<img width="1175" alt="Screen Shot 2022-10-16 at 10 02 50 am" src="https://user-images.githubusercontent.com/105696054/196010829-6638d6d8-fedb-4689-8e35-7799a29c8cb7.png">

**Comment by davidtaing** [comment]
Thanks for doing that for me!

Would you like to take on this issue?

And if so, how would approach the issue? Just testing you, not going to grill you 🙂.

**Comment by ghost** [comment]
Haha, nice one. 

Actually I deliberately wrote the issue as a simple “link it to external media” issue, however, to be thorough, I think we need to ask Dean if that’s sufficient, or if he would like internal blog pages on the site - which would require more issues! 😃

Warm Regards, 
Kathryn Kelly

**Comment by davidtaing** [comment]
Closing this issue for now as we've removed this section.
