### ISSUE TITLE
Top alignment issue with all pages except Home and About

### ISSUE THREAD

**Issue by engramar** [codesydney/lloydconsulting#40]
Except Home and About pages, it appears the rest of the pages have top alignment issue. See below. 

![lloyd](https://user-images.githubusercontent.com/7553347/196776313-00be0c88-fdf0-4ed8-98fb-e0e1563ca999.gif)

**Comment by davidtaing** [comment]
That's definitely a template issue. We might be able to fix this one with a negative margin.

I'll attend to this when I have time.

**Comment by engramar** [comment]
Thanks @davidtaing. No rush. Cheers.

**Comment by sfofthings** [comment]
great gif, how do you record it?

**Comment by davidtaing** [comment]
Closing this one for now since most of the sections were removed.
